server:
  port: 5555

spring:
  application:
    name: api-gateway
  cloud:
    config:
      uri: http://localhost:7001/

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/

feign:
  hystrix:
    enabled: true

zuul:
  routes:
    api-a-url:
      path: /api-hello/**
      ##url: http://localhost:8080/
      serviceId: hello-service
    feign-consumer:
      path: /api-feign-consumer/**
      ##url: http://localhost:9001/
      serviceId: feign-consumer