server:
  port: 5555

spring:
  application:
    name: api-gateway

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/

feign:
  hystrix:
    enabled: true

zuul:
  routes:
    api-a-url:
      path: /api-a-url/**
      url: http://localhost:8080/
